### ISSUE TITLE
TypeError  at line this.form_field_jq.trigger("change");

### ISSUE THREAD

**Issue by AH72KING** [harvesthq/chosen#2754]
I have joomla site of client and working on
 it issue i am facing is that when this line of code runs it give error
TypeError: ((n.event.special[g.origType] || (intermediate value)).handle || g.handler).apply is not a function

## It only happen some time 
you can say 30 times in 100 try

it tells me issue in jquery.min.js line 3
but error come due to 
at ( h.search_results_mouseup )
at Chosen.prototype.search_results_mouseup 
(https://www.newcastlebusinesscards.com.au/components/com_virtuemart/assets/js/chosen.jquery.min.js?vmver=9204:639:23)

```
 h.prototype.result_select = function(j) {
            var m, l, k, i;
            if (this.result_highlight) {
                m = this.result_highlight;
                l = m.attr("id");
                this.result_clear_highlight();
                if (this.is_multiple) {
                    this.result_deactivate(m)
                } else {
                    this.search_results.find(".result-selected").removeClass("result-selected");
                    this.result_single_selected = m
                }
                m.addClass("result-selected");
                i = l.substr(l.lastIndexOf("_") + 1);
                k = this.results_data[i];
                k.selected = true;
                this.form_field.options[k.options_index].selected = true;
                if (this.is_multiple) {
                    this.choice_build(k)
                } else {
                    this.selected_item.find("span").first().text(k.text);
                    if (this.allow_single_deselect) {
                        this.single_deselect_control_build()
                    }
                }
                if (!(j.metaKey && this.is_multiple)) {
                    this.results_hide()
                }
                this.search_field.val("");
                this.show_search_field_default();
       this.form_field_jq.trigger("change", {
           'selected': this.form_field.options[k.options_index].value
            });
               //this.form_field_jq.trigger("change");
                return this.search_field_scale()
 }


```

i do some console.log 
code not run after   this.form_field_jq.trigger("change" .. line
and even i do re select same error prints

see this chrome log 
```
TypeError: ((n.event.special[g.origType] || (intermediate value)).handle || g.handler).apply is not a function
    at HTMLSelectElement.dispatch (https://xxxxxxxx/media/jui/js/jquery.min.js:3:12444)
    at HTMLSelectElement.r.handle (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:3:9173)
    at Object.trigger (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:3:11573)
    at Object.a.event.trigger (https://www.xxxxxxxx.com.au/media/jui/js/jquery-migrate.min.js:2:8275)
    at HTMLSelectElement.<anonymous> (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:3:18991)
    at Function.each (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:2:2881)
    at a.fn.init.each (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:2:846)
    at a.fn.init.trigger (https://www.xxxxxxxx.com.au/media/jui/js/jquery.min.js:3:18967)
    at h.result_select (https://www.xxxxxxxx.com.au/components/com_virtuemart/assets/js/chosen.jquery.min.js?vmver=9204:756:30)
    at h.search_results_mouseup (https://www.xxxxxxxx.com.au/components/com_virtuemart/assets/js/chosen.jquery.min.js?vmver=9204:639:23)
```

**Comment by koenpunt** [comment]
The version of Chosen is at least 3 years old. If you can confirm you have the same issue with [the latest version](https://github.com/harvesthq/chosen/releases/tag/v1.6.2) of Chosen I will reopen this issue.
